version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "4443:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynetwork
    depends_on:
      - backend-service
      - frontend-service

  backend-service:
    build:
      context: .
      args:
        - TARGET=backend
    container_name: backend-service
    networks:
      - mynetwork

  frontend-service:
    build:
      context: .
      args:
        - TARGET=frontend
    container_name: frontend-service
    environment:
      - REACT_APP_BACKEND_URL=http://backend-service:3000
    networks:
      - mynetwork
    depends_on:
      - backend-service

  big_bear_libretranslate:
    container_name: big_bear_libretranslate
    image: libretranslate/libretranslate:v1.5.7
    restart: unless-stopped
    ports:
      - "5000:5000"
    tty: true
    healthcheck:
      test: ["CMD-SHELL", "./venv/bin/python scripts/healthcheck.py"]
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
