version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "4443:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynetwork
    depends_on:
      - backend-service
      - frontend-service

  backend-service:
    build:
      context: .
      args:
        - TARGET=backend
    container_name: backend-service
    networks:
      - mynetwork

  frontend-service:
    build:
      context: .
      args:
        - TARGET=frontend
    container_name: frontend-service
    environment:
      - REACT_APP_BACKEND_URL=http://backend-service:3000
    networks:
      - mynetwork
    depends_on:
      - backend-service

networks:
  mynetwork:
    driver: bridge
