version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "4443:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynetwork
    depends_on:
      - backend-service
      - frontend-service

  backend-service:
    build:
      context: ./api
    container_name: backend-service
    environment:
      - OPENAI_API_KEY=your_openai_api_key
    networks:
      - mynetwork

  frontend-service:
    build:
      context: ./client
    container_name: frontend-service
    environment:
      - REACT_APP_BACKEND_URL=http://backend-service:3000
    networks:
      - mynetwork
    volumes:
      - ./client/src:/app/src

networks:
  mynetwork:
    driver: bridge
